name: birdpress
description: A blogging engine in Flutter.
version: 0.0.1
homepage: https://github.com/imichaelnorris/birdpress

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  path_provider: ^2.0.10
  provider: ^6.0.3
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/birdpress/index.md
    # how to list everything in one directory?
    - assets/birdpress/posts/post1.md
    - assets/birdpress/posts/post2.md
