name: birdpress
description: A blogging engine in Flutter.
version: 0.0.1
homepage: https://github.com/imichaelnorris/birdpress

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  provider: ^6.0.3
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/birdpress/index.md
#    - assets/birdpress/*
